baseURL = "https://theme.dwye.dev/"
author = "Hugo authors"
theme = "dw-favored-blackburn"
copyright = "&copy; 2025. All rights reserved."
[pagination]
pagerSize = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
canonifyurls = true

[taxonomies]
  tag = "tags"
  topic = "topics"

[params]
  baseURL = "/"
  fullURL = "https://theme.dwye.dev"
  copyrightPage = "/"
  description = "dw-favored blackburn example site"
  brand = "Blackburn"
  # googleAnalytics = ""
  # disqus = ""
  dateFormat = "Jan 02, 2006"
  highlightjs = "vs2015"
  ReadingTime = true
  toc = true

  [params.social]
    linkedin = "dwy6626"
    github = "dwy6626"
    leetcode = "mirror0227"
  
  [params.utteranc]
    repo = "dwy6626/dw-favored-blackburn-example"

[languages]
  [languages.en]
    title = "A Sample Site"
    weight = 2
    contentDir = "content/en"
    languageName = "en"

    [languages.en.params]
      subtitle = "A man is only ever as strong as the people around him."
      from = "John Smith"

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "中文"
        pre = '<i class="fas fa-globe-asia fa-fw"></i>'
        weight = 100
        url = "zh"

      [[languages.en.menu.main]]
        name = "About"
        pre = "<i class='fas fa-user-circle fa-fw'></i>"
        weight = 3
        url = "about/"

      [[languages.en.menu.main]]
        name = "Posts"
        pre = "<i class='fas fa-list-ul fa-fw'></i>"
        weight = 10
        url = "post/"

      [[languages.en.menu.main]]
        name = "Topics"
        pre = '<i class="fas fa-folder fa-fw"></i>'
        weight = 20
        url = "topics/"

      [[languages.en.menu.main]]
        name = "Tags"
        pre = "<i class='fas fa-tags fa-fw'></i>"
        weight = 30
        url = "tags/"

  [languages.zh]
    title = "就...我記憶卡沒帶到"
    weight = 1
    languageName = "zh"
    contentDir = "content/zh"
    # for chinese: words are much "smaller" and thus more words should be shown
    summaryLength = 250
    hasCJKLanguage = true
    [languages.zh.params]
      subtitle = "啊我就怕被罵啊"
      from = "反正我很閒"
    [languages.zh.menu]

      [[languages.zh.menu.main]]
        name = "文章列表"
        pre = "<i class='fas fa-list-ul fa-fw'></i>"
        weight = 10
        url = "post/"

      [[languages.zh.menu.main]]
        name = "主題分類"
        pre = '<i class="fas fa-folder fa-fw"></i>'
        weight = 20
        url = "topics/"

      [[languages.zh.menu.main]]
        name = "標籤"
        pre = "<i class='fas fa-tags fa-fw'></i>"
        weight = 30
        url = "tags/"

      [[languages.zh.menu.main]]
        name = "English"
        pre = '<i class="fas fa-globe-americas fa-fw"></i>'
        weight = 100
        url = "../"

      [[languages.zh.menu.main]]
        name = "關於"
        pre = "<i class='fas fa-user-circle fa-fw'></i>"
        weight = 5
        url = "about/"
