name: Update Theme

on:
  repository_dispatch:


  workflow_dispatch:

jobs:
  update-theme:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 
          ref: master

      - name: update submodule
        run: |
          git submodule foreach git checkout master
          git submodule foreach --recursive git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add themes
          git commit -m "update submodule by github action"
          git push
